# Generated by Django 5.2 on 2025-04-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesthistory',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='report_photos/'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікує'), ('in_progress', 'Виконується'), ('done', 'Виконано')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікує'), ('in_progress', 'Виконується'), ('done', 'Виконано')], max_length=20),
        ),
    ]
