# Generated by Django 5.1.7 on 2025-04-15 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_requestphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requesthistory',
            name='photo',
        ),
    ]
