# Generated by Django 5.2 on 2025-04-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_remove_requesthistory_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='request_main_photos/'),
        ),
    ]
