# Generated by Django 5.1.7 on 2025-04-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('military', 'Військовий'), ('volunteer', 'Волонтер')], max_length=20),
        ),
    ]
