# Generated by Django 5.1.7 on 2025-04-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('волонтер', 'Волонтер'), ('військовий', 'Військовий')], default='волонтер', max_length=20),
        ),
    ]
