# Generated by Django 5.1.7 on 2025-04-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_type_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('волонтер', 'Волонтер'), ('військовий', 'Військовий')], max_length=20),
        ),
    ]
