# Generated by Django 5.2 on 2025-04-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='core/images/blank.png', upload_to='profile_pics/'),
        ),
    ]
